import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CheckCircle2, FileText, ShieldCheck } from "lucide-react";
import { ProductGallery } from "@/components/storefront/product-gallery";
import { ProductPurchase } from "@/components/storefront/product-purchase";
import { ProductDocumentationPanels } from "@/components/storefront/product-documentation";
import { CatalogGate } from "@/components/storefront/catalog-gate";
import { requireCatalogAccess } from "@/lib/commerce/gate";
import { getCommerceAdapter } from "@/lib/commerce/provider";
import { priceLabel } from "@/lib/commerce/format";

export async function generateMetadata({ params }: { params: Promise<{ handle: string }> }): Promise<Metadata> { const { handle } = await params; try { const product = await (await getCommerceAdapter()).getProduct(handle); return product ? { title: product.title, description: product.description || `Review specifications for ${product.title}.`, alternates: { canonical: `/products/${product.handle}` }, openGraph: { images: product.images[0]?.url ? [product.images[0].url] : [] } } : {}; } catch { return {}; } }
export default async function ProductPage({ params }: { params: Promise<{ handle: string }> }) { if (!(await requireCatalogAccess())) return <CatalogGate />; const { handle } = await params; const commerce = await getCommerceAdapter(); const product = await commerce.getProduct(handle).catch(() => null); if (!product) notFound(); const documentation = await commerce.getProductDocumentation(handle).catch(() => null); const jsonLd = { "@context": "https://schema.org", "@type": "Product", name: product.title, description: product.description, image: product.images.map((image) => image.url), offers: product.variants.map((variant) => ({ "@type": "Offer", priceCurrency: variant.price.currencyCode, price: variant.price.amount, availability: variant.availableForSale ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", url: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://cellovalabs.com"}/products/${product.handle}` })) }; return <section className="section"><div className="container"><div className="grid gap-9 lg:grid-cols-[0.95fr_1.05fr] lg:gap-14"><ProductGallery images={product.images} title={product.title} /><div className="py-2"><p className="eyebrow">{product.productType ?? "Product record"}</p><h1 className="font-display mt-3 text-4xl tracking-[-0.055em] text-[color:var(--indigo)] sm:text-5xl">{product.title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[color:var(--muted)]">{product.description || "Product details are supplied directly from the active commerce provider."}</p><p className="mt-6 font-mono text-[0.64rem] uppercase tracking-[0.08em] text-[color:var(--slate)]">{priceLabel(product.priceRange)}</p><ProductPurchase product={product} /><div className="mt-8 grid gap-3 border-t border-[color:var(--line)] pt-6 sm:grid-cols-3">{[{ icon: ShieldCheck, label: "Research use only" }, { icon: FileText, label: "Documentation when available" }, { icon: CheckCircle2, label: "Provider-backed product record" }].map(({ icon: Icon, label }) => <div key={label} className="flex items-start gap-2 text-[0.66rem] font-bold uppercase leading-5 tracking-[0.055em] text-[color:var(--indigo)]"><Icon size={16} className="mt-0.5 shrink-0 text-[color:var(--spark)]" strokeWidth={1.4} />{label}</div>)}</div></div></div><ProductDocumentationPanels data={documentation} /></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></section>; }
