import React, { useEffect, useState, type FormEvent } from "react";
import { Link, useRoute } from "wouter";
import { ArrowRight, CheckCircle2, FileText, Mail, PackageCheck, ShoppingBag } from "lucide-react";
import { useCart } from "@/contexts/CartContext";
import { createBrowserOrder, getBrowserOrder, listBrowserOrders, saveBrowserInquiry, type BrowserOrder } from "@/lib/browserRecords";
import { formatMoney, usePageMeta } from "@/lib/cellova";

export function FunctionalCheckoutPage() {
  usePageMeta("Checkout", "Complete your Cellova research order.");
  const { cart, proceedToCheckout } = useCart();
  const [order, setOrder] = useState<BrowserOrder | null>(null);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!cart?.items.length) return;
    const form = new FormData(event.currentTarget);
    setOrder(createBrowserOrder(cart, { name: `${form.get("firstName")} ${form.get("lastName")}`, email: String(form.get("email") ?? ""), address: String(form.get("address") ?? ""), city: String(form.get("city") ?? ""), state: String(form.get("state") ?? ""), postalCode: String(form.get("postalCode") ?? "") }));
  }
  if (!cart?.items.length && !order) return <main className="page-main"><section className="site-width orders-page"><p className="eyebrow eyebrow--spark">CHECKOUT</p><h1>Start with a research order.</h1><div className="empty-catalog"><ShoppingBag size={30} /><p>Your cart is empty.</p><Link href="/products" className="button button--spark">Browse products <ArrowRight size={16} /></Link></div></section></main>;
  return <main className="page-main"><section className="site-width checkout-page"><div><p className="eyebrow eyebrow--spark">SECURE CHECKOUT</p><h1>Research order details.</h1><p>Save the delivery details for this browser, then continue to the secure checkout provided by the selected commerce provider.</p></div>{order ? <div className="form-confirmation"><CheckCircle2 size={36} /><p className="eyebrow eyebrow--spark">ORDER PREPARED</p><h2>Research order {order.id}</h2><p>Order preparation is recorded locally for this browser. Use the provider checkout to complete payment and fulfillment.</p><div className="flow-actions"><button className="button button--spark" disabled={!cart?.checkoutUrl} onClick={proceedToCheckout}>Open secure checkout <ArrowRight size={16} /></button><Link className="button button--ink" href={`/account/orders/${order.id}`}>View order record</Link></div></div> : <form onSubmit={submit} className="checkout-form"><h2>Shipping and billing</h2><div className="form-split"><label>First name<input name="firstName" required autoComplete="given-name" /></label><label>Last name<input name="lastName" required autoComplete="family-name" /></label></div><label>Email<input name="email" required type="email" autoComplete="email" /></label><label>Address<input name="address" required autoComplete="street-address" /></label><div className="form-split"><label>City<input name="city" required autoComplete="address-level2" /></label><label>State<input name="state" required autoComplete="address-level1" /></label></div><label>Postal code<input name="postalCode" required autoComplete="postal-code" /></label><label className="consent"><input type="checkbox" required /><span>I confirm this order is for lawful research use and accept the Cellova research-use disclosure.</span></label><button className="button button--spark button--wide" type="submit">Prepare research order <ArrowRight size={16} /></button></form>}</section></main>;
}

export function FunctionalContactPage() {
  usePageMeta("Contact", "Contact Cellova Labs.");
  const [inquiryId, setInquiryId] = useState<string | null>(null);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const inquiry = saveBrowserInquiry({ name: String(form.get("name") ?? ""), email: String(form.get("email") ?? ""), topic: String(form.get("topic") ?? ""), message: String(form.get("message") ?? "") }); setInquiryId(inquiry.id); }
  return <main className="page-main"><section className="site-width contact-page"><div><p className="eyebrow eyebrow--spark">CONTACT</p><h1>Speak with the Cellova team.</h1><p>Use this form for research catalog, documentation, and order-support inquiries.</p><div className="contact-page__details"><Mail size={22} /><span>Your submitted inquiry is saved in this browser until the production Cellova support service is connected.</span></div></div>{inquiryId ? <div className="form-confirmation"><Mail size={36} /><p className="eyebrow eyebrow--spark">INQUIRY SAVED</p><h2>Reference {inquiryId}</h2><p>Your inquiry has been saved in this browser. Configure the Cellova support integration to transmit new inquiries to the support team.</p><button className="button button--ink" onClick={() => setInquiryId(null)}>Create another inquiry</button></div> : <form className="checkout-form" onSubmit={submit}><label>Name<input name="name" required /></label><label>Email<input name="email" required type="email" /></label><label>Topic<select name="topic" required defaultValue=""><option value="" disabled>Select a topic</option><option value="catalog">Catalog information</option><option value="documentation">Documentation</option><option value="order">Research order support</option></select></label><label>Message<textarea name="message" required rows={6} /></label><button className="button button--spark button--wide">Save inquiry <ArrowRight size={16} /></button></form>}</section></main>;
}

export function FunctionalOrdersPage() {
  usePageMeta("Order history", "Cellova research order history.");
  const [orders, setOrders] = useState<BrowserOrder[]>(() => typeof window === "undefined" ? [] : listBrowserOrders());
  useEffect(() => setOrders(listBrowserOrders()), []);
  return <main className="page-main"><section className="site-width orders-page"><p className="eyebrow eyebrow--spark">ORDER HISTORY</p><h1>Research orders</h1>{orders.length ? <div className="orders-table"><div className="orders-table__head"><span>Order</span><span>Prepared</span><span>Status</span><span>Total</span><span /></div>{orders.map(order => <div key={order.id}><strong>{order.id}</strong><span>{new Date(order.createdAt).toLocaleDateString()}</span><span className="order-status">Prepared</span><span>{formatMoney(order.total.amount, order.total.currencyCode)}</span><Link href={`/account/orders/${order.id}`}>View <ArrowRight size={15} /></Link></div>)}</div> : <div className="empty-catalog"><PackageCheck size={30} /><h3>No prepared research orders yet.</h3><p>Prepare an order at checkout and it will appear here in this browser.</p><Link className="button button--spark" href="/products">Browse catalog <ArrowRight size={16} /></Link></div>}</section></main>;
}

export function FunctionalOrderDetailPage() {
  const [, params] = useRoute<{ id: string }>("/account/orders/:id");
  const [order, setOrder] = useState<BrowserOrder | null>(() => typeof window === "undefined" || !params?.id ? null : getBrowserOrder(params.id));
  useEffect(() => { if (params?.id) setOrder(getBrowserOrder(params.id)); }, [params?.id]);
  usePageMeta(order ? `Order ${order.id}` : "Order details", "Cellova research order details.");
  return <main className="page-main"><section className="site-width orders-page"><Link className="text-link" href="/account/orders">← Back to order history</Link><p className="eyebrow eyebrow--spark">ORDER RECORD</p><h1>{order ? order.id : "Order unavailable"}</h1>{order ? <div className="order-detail"><div><h2>Prepared order</h2><p>Created {new Date(order.createdAt).toLocaleString()}</p><p><span className="order-status">Prepared</span></p><h3>Delivery details</h3><p>{order.customer.name}<br />{order.customer.address}<br />{order.customer.city}, {order.customer.state} {order.customer.postalCode}<br />{order.customer.email}</p></div><div><h2>Materials</h2>{order.items.map(item => <article key={item.lineId}><span>{item.quantity} ×</span><div><strong>{item.productTitle}</strong><small>{item.variantTitle}</small></div><b>{formatMoney(item.lineTotal.amount, item.lineTotal.currencyCode)}</b></article>)}<dl><div><dt>Subtotal</dt><dd>{formatMoney(order.subtotal.amount, order.subtotal.currencyCode)}</dd></div><div><dt>Total</dt><dd>{formatMoney(order.total.amount, order.total.currencyCode)}</dd></div></dl></div></div> : <div className="empty-catalog"><FileText size={30} /><h3>This order record is unavailable.</h3><p>Prepared orders are only visible in the same browser until provider-backed customer-order retrieval is configured.</p></div>}</section></main>;
}
