import { FormEvent, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowRight, ChevronRight, FileText, LoaderCircle, Mail, PackageCheck, Search, ShoppingBag, Trash2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { CELLLOVA_ASSETS, formatMoney, usePageMeta } from "@/lib/cellova";
import { useCart } from "@/contexts/CartContext";
import { useResearchAccess } from "@/contexts/ResearchAccessContext";

type CatalogSort = "featured" | "alphabetical" | "price-low" | "price-high";

function ProductCards({ collectionHandle }: { collectionHandle?: string }) {
  const productsQuery = trpc.commerce.products.list.useQuery({ first: 50, collectionHandle });
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState<CatalogSort>("featured");
  const products = useMemo(() => {
    const next = (productsQuery.data ?? []).filter(product => `${product.title} ${product.productType ?? ""}`.toLowerCase().includes(search.toLowerCase()));
    return [...next].sort((a, b) => sort === "alphabetical" ? a.title.localeCompare(b.title) : sort === "price-low" ? Number(a.priceRange.min.amount) - Number(b.priceRange.min.amount) : sort === "price-high" ? Number(b.priceRange.min.amount) - Number(a.priceRange.min.amount) : 0);
  }, [productsQuery.data, search, sort]);
  if (productsQuery.isLoading) return <div className="loading-page"><LoaderCircle size={26} className="spin" />Loading catalog…</div>;
  return <><div className="catalog-toolbar"><label><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search research materials" /></label><label>Sort<select value={sort} onChange={event => setSort(event.target.value as CatalogSort)}><option value="featured">Featured</option><option value="alphabetical">Alphabetical</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div>{products.length ? <div className="parity-product-grid">{products.map(product => <article key={product.id}><Link href={`/products/${product.handle}`}><img src={product.images[0]?.url || CELLLOVA_ASSETS.product} alt={product.images[0]?.altText || `${product.title} product presentation`} /></Link><div><p>{product.productType || "RESEARCH MATERIAL"}</p><h3><Link href={`/products/${product.handle}`}>{product.title}</Link></h3><span>{product.lotDocumentation ? "Lot documentation available" : "Documentation pending"}</span><footer><strong>{formatMoney(product.priceRange.min.amount, product.priceRange.min.currencyCode)}</strong><Link className="button button--spark button--small" href={`/products/${product.handle}`}>View record <ArrowRight size={14} /></Link></footer></div></article>)}</div> : <div className="empty-catalog"><p className="eyebrow">NO MATCHES</p><h3>No catalog records match the current filter.</h3><p>Clear your search or adjust the product data in the active commerce provider.</p></div>}</>;
}

export function ProductsPage() {
  usePageMeta("Products", "Browse the Cellova Labs research materials catalog.");
  return <main className="page-main"><section className="catalog-header"><div className="site-width"><p className="eyebrow eyebrow--spark">RESEARCH CATALOG</p><h1>Materials with a<br /><em>clear record.</em></h1><p>Browse Cellova research material records, documentation status, and available product formats.</p></div></section><section className="site-width parity-catalog"><div className="breadcrumb"><Link href="/">Home</Link><ChevronRight size={14} /><span>Products</span></div><ProductCards /></section></main>;
}

export function CollectionsPage() {
  usePageMeta("Collections", "Explore Cellova Labs research-material collections.");
  const collectionsQuery = trpc.commerce.collections.list.useQuery({ first: 24 });
  return <main className="page-main"><section className="catalog-header"><div className="site-width"><p className="eyebrow eyebrow--spark">RESEARCH COLLECTIONS</p><h1>Catalogs organized<br /><em>by research focus.</em></h1><p>Browse collections published by the active commerce provider.</p></div></section><section className="site-width parity-collections">{collectionsQuery.isLoading ? <div className="loading-page"><LoaderCircle size={26} className="spin" />Loading collections…</div> : collectionsQuery.data?.length ? <div>{collectionsQuery.data.map(collection => <Link key={collection.id} href={`/collections/${collection.handle}`} className="collection-card">{collection.image ? <img src={collection.image.url} alt={collection.image.altText || ""} /> : <div className="collection-card__blank"><FileText size={28} /></div>}<span>COLLECTION</span><h2>{collection.title}</h2><p>{collection.description || "Explore available research material records."}</p><b>Open collection <ArrowRight size={16} /></b></Link>)}</div> : <div className="empty-catalog"><p className="eyebrow">COLLECTIONS PENDING</p><h3>Collections will appear when configured in the active provider.</h3><p>Shopify collections and Medusa collections are normalized through the same storefront route.</p></div>}</section></main>;
}

export function CollectionDetailPage() {
  const [, params] = useRoute<{ handle: string }>("/collections/:handle");
  const handle = params?.handle ?? "";
  const collectionQuery = trpc.commerce.collections.byHandle.useQuery({ handle }, { enabled: Boolean(handle) });
  usePageMeta(collectionQuery.data?.title || "Collection", "Cellova Labs research collection.");
  if (collectionQuery.isLoading) return <main className="page-main"><div className="site-width loading-page"><LoaderCircle className="spin" />Loading collection…</div></main>;
  if (!collectionQuery.data) return <main className="page-main"><div className="site-width not-found-panel"><p className="eyebrow">COLLECTION</p><h1>This collection is unavailable.</h1><Link className="button button--ink" href="/collections">Back to collections</Link></div></main>;
  const collection = collectionQuery.data;
  return <main className="page-main"><section className="collection-detail-hero">{collection.image && <img src={collection.image.url} alt="" />}<div className="site-width"><div className="breadcrumb"><Link href="/collections">Collections</Link><ChevronRight size={14} /><span>{collection.title}</span></div><p className="eyebrow eyebrow--spark">RESEARCH COLLECTION</p><h1>{collection.title}</h1><p>{collection.description || "Published research materials for the selected Cellova collection."}</p></div></section><section className="site-width parity-catalog"><ProductCards collectionHandle={handle} /></section></main>;
}

export function CartPage() {
  usePageMeta("Cart", "Review your Cellova research order.");
  const { cart, loading, error, updateQuantity, removeItem, proceedToCheckout } = useCart();
  return <main className="page-main"><section className="site-width cart-page"><p className="eyebrow eyebrow--spark">RESEARCH ORDER</p><h1>Your cart</h1>{!cart?.items.length ? <div className="empty-catalog"><ShoppingBag size={30} /><h3>Your research order is empty.</h3><p>Add a material from the gated catalog to begin an order.</p><Link href="/products" className="button button--spark">Browse products <ArrowRight size={16} /></Link></div> : <div className="cart-page__grid"><div className="cart-page__lines">{cart.items.map(item => <article key={item.lineId}><img src={item.image?.url || CELLLOVA_ASSETS.product} alt="" /><div><p>{item.productHandle}</p><h2>{item.productTitle}</h2><span>{item.variantTitle}</span><strong>{formatMoney(item.unitPrice.amount, item.unitPrice.currencyCode)}</strong></div><div className="cart-page__actions"><div className="quantity-stepper"><button type="button" onClick={() => updateQuantity(item.lineId, item.quantity - 1)}>−</button><span>{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.lineId, item.quantity + 1)}>+</button></div><button type="button" onClick={() => removeItem(item.lineId)} aria-label={`Remove ${item.productTitle}`}><Trash2 size={17} /></button></div></article>)}</div><aside><p className="eyebrow eyebrow--spark">ORDER SUMMARY</p><dl><div><dt>Subtotal</dt><dd>{formatMoney(cart.subtotal.amount, cart.subtotal.currencyCode)}</dd></div><div><dt>Research order total</dt><dd>{formatMoney(cart.total.amount, cart.total.currencyCode)}</dd></div></dl>{error && <p className="purchase-panel__error">{error}</p>}<button type="button" className="button button--spark button--wide" disabled={loading || !cart.checkoutUrl} onClick={proceedToCheckout}>Continue to checkout <ArrowRight size={16} /></button>{!cart.checkoutUrl && <p className="cart-page__notice">The selected commerce provider needs a checkout handoff URL before orders can be completed.</p>}<p className="cart-page__notice">All materials are supplied for research use only.</p></aside></div>}</section></main>;
}

export function CheckoutPage() {
  usePageMeta("Checkout", "Complete your Cellova research order.");
  const { cart, proceedToCheckout } = useCart();
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <main className="page-main"><section className="site-width checkout-page"><div><p className="eyebrow eyebrow--spark">SECURE CHECKOUT</p><h1>Research order details.</h1><p>Provide shipping information, then continue to the secure checkout supplied by the active commerce provider.</p></div>{submitted ? <div className="form-confirmation"><PackageCheck size={36} /><p className="eyebrow eyebrow--spark">READY TO CONTINUE</p><h2>Order details reviewed.</h2><p>{cart?.checkoutUrl ? "Continue to the secure provider checkout to complete the research order." : "The active commerce provider needs a checkout handoff URL before this order can continue."}</p><button className="button button--spark" disabled={!cart?.checkoutUrl} onClick={proceedToCheckout}>Open secure checkout <ArrowRight size={16} /></button></div> : <form onSubmit={submit} className="checkout-form"><h2>Shipping and billing</h2><div className="form-split"><label>First name<input required autoComplete="given-name" /></label><label>Last name<input required autoComplete="family-name" /></label></div><label>Email<input required type="email" autoComplete="email" /></label><label>Address<input required autoComplete="street-address" /></label><div className="form-split"><label>City<input required autoComplete="address-level2" /></label><label>State<input required autoComplete="address-level1" /></label></div><label>Postal code<input required autoComplete="postal-code" /></label><label className="consent"><input type="checkbox" required /><span>I confirm this order is for lawful research use and accept the Cellova research-use disclosure.</span></label><button className="button button--spark button--wide" type="submit">Review secure checkout <ArrowRight size={16} /></button></form>}</section></main>;
}

export function AboutPage() { usePageMeta("About", "How Cellova Labs organizes a research-use catalog."); return <main className="page-main"><section className="site-width editorial-page"><p className="eyebrow eyebrow--spark">ABOUT CELLOVA</p><h1>Operating from the product record.</h1><p className="editorial-page__lead">Cellova Labs is built around clear research-material records, controlled catalog access, and documentation that stays connected to the lot it describes.</p><div className="editorial-page__cards"><article><span>01</span><h2>Research focus</h2><p>Material records prioritize useful technical context over broad claims.</p></article><article><span>02</span><h2>Documentation standards</h2><p>Published lot data is visible alongside the product where available.</p></article><article><span>03</span><h2>Controlled access</h2><p>Catalog and ordering workflows are structured for research-account access.</p></article></div></section></main>; }

export function ContactPage() { usePageMeta("Contact", "Contact Cellova Labs."); const [submitted, setSubmitted] = useState(false); return <main className="page-main"><section className="site-width contact-page"><div><p className="eyebrow eyebrow--spark">CONTACT</p><h1>Speak with the Cellova team.</h1><p>Use this form for research catalog, documentation, and order-support inquiries.</p><div className="contact-page__details"><Mail size={22} /><span>Response details will be configured with the Cellova support address before launch.</span></div></div>{submitted ? <div className="form-confirmation"><Mail size={36} /><h2>Message prepared.</h2><p>The production contact route must be configured before messages are transmitted.</p><button className="button button--ink" onClick={() => setSubmitted(false)}>Send another message</button></div> : <form className="checkout-form" onSubmit={event => { event.preventDefault(); setSubmitted(true); }}><label>Name<input required /></label><label>Email<input required type="email" /></label><label>Topic<select required defaultValue=""><option value="" disabled>Select a topic</option><option value="catalog">Catalog information</option><option value="documentation">Documentation</option><option value="order">Research order support</option></select></label><label>Message<textarea required rows={6} /></label><button className="button button--spark button--wide">Submit inquiry <ArrowRight size={16} /></button></form>}</section></main>; }

export function AccountDashboardPage() { const { account, logout } = useResearchAccess(); usePageMeta("Account", "Manage your Cellova research account."); if (!account) return <main className="page-main"><section className="site-width account-page"><div><p className="eyebrow eyebrow--spark">ACCOUNT ACCESS</p><h1>Sign in to your research account.</h1><p>The global research gate provides account registration and sign-in before catalog access.</p></div></section></main>; return <main className="page-main"><section className="site-width account-dashboard"><div><p className="eyebrow eyebrow--spark">RESEARCH ACCOUNT</p><h1>Welcome, {account.firstName}.</h1><p>Manage the Cellova research account used to access the controlled catalog.</p></div><article><p className="product-tech">PROFILE</p><h2>{account.firstName} {account.lastName}</h2><p>{account.email}<br />{account.companyName}</p><button className="button button--ink" onClick={logout}>Sign out</button></article><article><p className="product-tech">ORDER HISTORY</p><h2>Research orders</h2><p>Review available order records and their associated documentation.</p><Link className="button button--spark" href="/account/orders">View orders <ArrowRight size={16} /></Link></article><article><p className="product-tech">CATALOG ACCESS</p><h2>Continue research</h2><p>Return to the controlled Cellova product catalog.</p><Link className="button button--spark" href="/products">Browse products <ArrowRight size={16} /></Link></article></section></main>; }

export function OrdersPage() { usePageMeta("Order history", "Cellova research order history."); return <main className="page-main"><section className="site-width orders-page"><p className="eyebrow eyebrow--spark">ORDER HISTORY</p><h1>Research orders</h1><div className="empty-catalog"><PackageCheck size={30} /><h3>No orders are available in this account.</h3><p>Orders from the active Shopify or Medusa provider will appear here once customer-order integration is configured.</p><Link className="button button--spark" href="/products">Browse catalog <ArrowRight size={16} /></Link></div></section></main>; }

export function OrderDetailPage() { const [, params] = useRoute<{ id: string }>("/account/orders/:id"); usePageMeta("Order details", "Cellova research order details."); return <main className="page-main"><section className="site-width orders-page"><Link className="text-link" href="/account/orders">← Back to order history</Link><p className="eyebrow eyebrow--spark">ORDER RECORD</p><h1>Order {params?.id || "unavailable"}</h1><div className="empty-catalog"><FileText size={30} /><h3>This order record is unavailable.</h3><p>Connect provider-backed customer-order retrieval to display authorized order details, shipment information, and line-item documentation.</p></div></section></main>; }

const policyCopy: Record<string, [string, string, string]> = { terms: ["Terms of use", "Cellova Labs provides controlled research-catalog information and materials. Site visitors are responsible for reviewing all product documentation and disclosures.", "Materials are for lawful research use only and are not intended for human or veterinary use."], privacy: ["Privacy policy", "Cellova will collect only the information necessary to administer account access, research orders, and support once production integrations are configured.", "Final retention practices and contact information must be reviewed before launch."], "research-use": ["Research-use policy", "Products are presented for research use only. Review every product record and lot document before using catalog information for research planning.", "The catalog does not provide medical, treatment, or diagnostic guidance."], shipping: ["Shipping policy", "Order fulfillment and shipping options are supplied by the active commerce provider and finalized during checkout.", "Review the current provider checkout for location, timing, and shipping-cost details."], returns: ["Returns policy", "Return eligibility and order discrepancies are handled through the final provider-backed customer support workflow.", "Contact the Cellova support team through the configured production support channel for assistance."] };
export function ExtendedPolicyPage() { const [, params] = useRoute<{ policy: string }>("/policies/:policy"); const content = policyCopy[params?.policy || "terms"] || policyCopy.terms; usePageMeta(content[0], `${content[0]} for Cellova Labs.`); return <main className="page-main"><article className="site-width policy-page"><p className="eyebrow eyebrow--spark">CELLOVA LABS / POLICY</p><h1>{content[0]}</h1><div className="policy-page__body"><p>{content[1]}</p><p>{content[2]}</p><p className="policy-page__revision">Last reviewed: September 2026. Final legal review is required before launch.</p></div></article></main>; }
