"use client";

import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import type { Product, ProductPage } from "@/lib/commerce/types";
import { ProductGrid } from "./product-grid";

export function CatalogExplorer({ products: initialProducts, collectionTitle, collectionHandle, initialNextCursor, initialHasNextPage }: { products: Product[]; collectionTitle?: string; collectionHandle?: string; initialNextCursor?: string | null; initialHasNextPage?: boolean }) {
  const [products, setProducts] = useState(initialProducts); const [nextCursor, setNextCursor] = useState(initialNextCursor ?? null); const [hasNextPage, setHasNextPage] = useState(initialHasNextPage ?? false); const [loadingMore, setLoadingMore] = useState(false); const [loadError, setLoadError] = useState<string | null>(null);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [sort, setSort] = useState("title");
  const filters = useMemo(() => ["all", ...Array.from(new Set(products.map((product) => product.productType?.trim()).filter((type): type is string => Boolean(type))))], [products]);
  const visible = useMemo(() => products.filter((product) => { const needle = query.toLowerCase(); const matchesQuery = !needle || [product.title, product.productType ?? "", product.tags.join(" ")].join(" ").toLowerCase().includes(needle); const matchesFilter = filter === "all" || product.productType === filter || product.tags.includes(filter); return matchesQuery && matchesFilter; }).sort((a, b) => sort === "price-low" ? Number(a.priceRange.min.amount) - Number(b.priceRange.min.amount) : sort === "price-high" ? Number(b.priceRange.min.amount) - Number(a.priceRange.min.amount) : a.title.localeCompare(b.title)), [products, query, filter, sort]);
  if (!products.length) return <ProductGrid products={products} />;
  async function loadMore() { if (!nextCursor || loadingMore) return; setLoadingMore(true); setLoadError(null); try { const params = new URLSearchParams({ after: nextCursor }); if (collectionHandle) params.set("collection", collectionHandle); const response = await fetch(`/api/catalog?${params}`); const page = await response.json() as ProductPage & { message?: string }; if (!response.ok) throw new Error(page.message ?? "The catalog could not load more products."); setProducts((current) => [...current, ...page.products]); setNextCursor(page.nextCursor); setHasNextPage(page.hasNextPage); } catch (error) { setLoadError(error instanceof Error ? error.message : "The catalog could not load more products."); } finally { setLoadingMore(false); } }
  return <div><div className="mb-7 grid gap-3 rounded-2xl border border-[color:var(--line)] bg-white p-3 sm:grid-cols-[1fr_auto_auto]"><label className="flex items-center gap-2 rounded-xl bg-[color:var(--paper)] px-3"><Search size={17} className="text-[color:var(--slate)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={collectionTitle ? `Search ${collectionTitle}` : "Search the catalog"} className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[color:var(--muted)]" /></label><label className="flex items-center gap-2 rounded-xl border border-[color:var(--line)] px-3 text-sm"><SlidersHorizontal size={16} className="text-[color:var(--slate)]" /><select aria-label="Filter products" value={filter} onChange={(event) => setFilter(event.target.value)} className="h-11 min-w-[8rem] bg-transparent outline-none">{filters.map((item) => <option key={item} value={item}>{item === "all" ? "All formats" : item}</option>)}</select></label><label className="flex items-center gap-2 rounded-xl border border-[color:var(--line)] px-3 text-sm"><span className="text-[color:var(--muted)]">Sort</span><select aria-label="Sort products" value={sort} onChange={(event) => setSort(event.target.value)} className="h-11 bg-transparent outline-none"><option value="title">Name</option><option value="price-low">Price: low</option><option value="price-high">Price: high</option></select></label></div>{visible.length ? <><ProductGrid products={visible} />{hasNextPage && <div className="mt-9 text-center"><button onClick={loadMore} disabled={loadingMore} className="button-quiet">{loadingMore ? "Loading catalog" : "Load more products"}</button>{loadError && <p className="mt-3 text-sm text-[#8e3c2d]">{loadError}</p>}</div>}</> : <div className="surface py-16 text-center"><p className="eyebrow">No matching records</p><h2 className="mt-3 font-display text-xl text-[color:var(--indigo)]">Adjust your search or filters.</h2><button onClick={() => { setQuery(""); setFilter("all"); }} className="button-quiet mt-5">Reset filters</button></div>}</div>;
}
