"use client";

import { useMemo, useState } from "react";
import { Download, FileSearch, Search } from "lucide-react";
import type { COAData } from "@/lib/commerce/types";

export function CoaLibraryExplorer({ records }: { records: COAData[] }) {
  const [query, setQuery] = useState(""); const visible = useMemo(() => records.filter((record) => [record.productName, record.lotNumber, record.testedDate, record.laboratory].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase())), [records, query]);
  return <div><label className="flex max-w-xl items-center gap-2 rounded-xl border border-[color:var(--line)] bg-white px-4"><Search size={18} className="text-[color:var(--slate)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search product, lot, or date" className="h-12 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[color:var(--muted)]" /></label>{!visible.length ? <div className="surface mt-7 py-16 text-center"><FileSearch className="mx-auto text-[color:var(--slate)]" size={30} strokeWidth={1.3} /><h2 className="font-display mt-5 text-xl text-[color:var(--indigo)]">{records.length ? "No matching certificate records." : "No certificate records are available yet."}</h2><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-[color:var(--muted)]">Only certificates with an available provider document are listed here.</p></div> : <div className="mt-7 overflow-hidden rounded-2xl border border-[color:var(--line)] bg-white"><div className="hidden grid-cols-[1.2fr_0.75fr_0.75fr_auto] gap-5 border-b border-[color:var(--line)] bg-[color:var(--paper)] px-6 py-4 font-mono text-[0.6rem] uppercase tracking-[0.08em] text-[color:var(--slate)] sm:grid"><span>Product</span><span>Lot / batch</span><span>Test date</span><span>Document</span></div>{visible.map((record) => <article key={`${record.productHandle}-${record.pdfUrl}`} className="grid gap-2 border-b border-[color:var(--line)] px-6 py-5 last:border-0 sm:grid-cols-[1.2fr_0.75fr_0.75fr_auto] sm:items-center sm:gap-5"><h2 className="font-display text-[1rem] text-[color:var(--indigo)]">{record.productName}</h2><p className="font-mono text-[0.67rem] uppercase tracking-[0.06em] text-[color:var(--muted)]">{record.lotNumber ?? "Record available"}</p><p className="text-sm text-[color:var(--muted)]">{record.testedDate ?? "Date available in document"}</p>{record.pdfUrl && <a href={record.pdfUrl} target="_blank" rel="noreferrer" className="button-quiet shrink-0">View PDF <Download size={14} /></a>}</article>)}</div>}</div>;
}
