import { Download, FileCheck2, FlaskConical, ShieldAlert } from "lucide-react";
import type { ProductDocumentation } from "@/lib/commerce/types";

export function ProductDocumentationPanels({ data }: { data: ProductDocumentation | null }) {
  const coa = data?.coa;
  const records = coa ? [["Product", coa.productName], ["Lot number", coa.lotNumber], ["Tested date", coa.testedDate], ["Laboratory", coa.laboratory], ["Identity", coa.identity], ["Purity", coa.purity], ["Net content", coa.netContent], ["Endotoxin", coa.endotoxin], ["Heavy metals", coa.heavyMetals]].filter(([, value]) => Boolean(value)) : [];
  return <section className="mt-14 border-t border-[color:var(--line)] pt-10"><div className={`grid gap-4 ${records.length ? "lg:grid-cols-2" : ""}`}>{records.length ? <article className="rounded-2xl border border-[color:var(--line)] bg-white p-6"><div className="flex items-center gap-3"><FileCheck2 size={20} strokeWidth={1.45} className="text-[color:var(--spark)]" /><h2 className="font-display text-xl text-[color:var(--indigo)]">Certificate of analysis</h2></div><dl className="mt-6 divide-y divide-[color:var(--line)]">{records.map(([label, value]) => <div key={label} className="grid grid-cols-[minmax(6.5rem,0.75fr)_1.25fr] gap-4 py-3 text-sm"><dt className="font-mono text-[0.63rem] uppercase tracking-[0.05em] text-[color:var(--slate)]">{label}</dt><dd className="text-[color:var(--indigo)]">{value}</dd></div>)}</dl>{coa?.pdfUrl && <a href={coa.pdfUrl} target="_blank" rel="noreferrer" className="button-secondary mt-6">View COA document <Download size={15} /></a>}</article> : null}
    <div className="grid gap-4"><article className="rounded-2xl border border-[color:var(--line)] bg-white p-6"><div className="flex items-center gap-3"><FlaskConical size={20} strokeWidth={1.45} className="text-[color:var(--spark)]" /><h2 className="font-display text-xl text-[color:var(--indigo)]">Storage instructions</h2></div><p className="mt-5 text-sm leading-7 text-[color:var(--muted)]">{data?.storageInstructions ?? "Storage information is provided with the product record when available."}</p></article><article className="rounded-2xl border border-[color:var(--line)] bg-white p-6"><div className="flex items-center gap-3"><ShieldAlert size={20} strokeWidth={1.45} className="text-[color:var(--spark)]" /><h2 className="font-display text-xl text-[color:var(--indigo)]">Intended use</h2></div><p className="mt-5 text-sm leading-7 text-[color:var(--muted)]">{data?.intendedUse ?? "For research use only. Product-specific intended-use information is supplied when available."}</p></article></div>
  </div></section>;
}
